version: '3.8'

services:
  php:
    container_name: laravel-app-php
#    image: php:8.3-fpm
    build:
      context: .
#      dockerfile: Dockerfile
      dockerfile: docker/php/Dockerfile
      args:
          USER_ID: ${DOCKER_USER_ID}
          GROUP_ID: ${DOCKER_GROUP_ID}
    volumes:
      - .:/var/www/html
#      - ./public:/var/www/html/public
#      - ./docker/nginx:/var/www/html/nginx
#      - ./docker/php:/usr/local/etc/php # Optional if you have custom PHP configs
    networks:
      - app-network
    depends_on:
        - mysql

  nginx:
    container_name: laravel-app-nginx
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - php

  mysql:
      container_name: laravel-app-mysql
      image: mysql:8.0
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      ports:
         - 33061:${DB_PORT} # hostPort:containerPort
#        - "33061:3306" # hostPort:containerPort
      volumes:
          - mysql_data:/var/lib/mysql
      networks:
          - app-network

networks:
  app-network:
    driver: bridge

volumes:
    mysql_data:
        driver: local
